[package]
name = "polychromatist/thor"
version = "0.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "thor (three+four) - your tool for geometric algebra kernels"
authors = ["polychromatist"]

[dependencies]

[dev-dependencies]
testez = "roblox/testez@0.4.1"
